sudo: false
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
- rm -rf target
script: "./travis-build.sh"
env:
  global:
  - secure: kKu24VXKioUXvD2CWZbmQq3MXnKlr0XGgURYXsJU+0CZxXZ5Y3BvAidR+Vd6LX2dOOxPvfHWNZcSUlb2oq2RxEEVa+CKO9oOCLL5gywn4NpeGbzNbeoACvbxHRLYVc8bnaFvXm6J/4LjNKJdbgCESzjeu89O8iSChWgk5rk6JBb3e42SsOj9iY0rfuzTrNKI+z6xv1frm+ztsrqsWYw4KSGK+qPPdz5WEeAJfDlYOgwq9TLHXd1jimzZs5XYkMx15dtJ6dl2iX1V4RNYa03Kg6UoiBnlYyF+UGiyLOKm98gLjQg7k141xvHtVXk23TNBdS5BbuGpCklK644GdtCURGupH3beiN6ZrF89qrXgM8PYrLKsoeBBlji76/BjZCL8Egad6/b+dxXED3DFcAcHgiAKo23OTzCYYmu6lARt6j4BWxDuC+RE1M6VWDVtUVvjtOboHGvr2is9RWyQBXzPlKQziv95D9ljX8LUQvcF01vk5ORJqa1mxkPp68RqgBx0howpZxikYoy8pW+yBhnrEu5ABv4YfxUcNM1ReGsM3IA/KxttvuQPnsBBzT92ByWCm57ZVRHrp6ZmiJAy3GilYPN4efEi0Zccte8L295rAaGs3R8AzIJmzOys9ugFj9JS4ObaPe4cHtn8ApclkzI/03njzDwixN7pUgOZa3FEt5M=
  - secure: S/yAT5DkdgCxtguQdoWcRUEPw/+EF/SqW8FJJ6kpwPu+gwx6aD/zDEqarotd7eNtNZCW6F+Z2/hKLiOxwWryyr0SFbuhZp75avw+zXOWRDG1TWfWI6oTFLGCtKkS4D76/E8ec3rvMLaT/dKnm8I6XBxkBQ3ESy+b2Yd0nCrbWFpm/Ni7UXhD9eUInmEb+1kHuHAoF2RXmrTzKuDf2Agt8sMKYmqEy/5tq6lYkMY3eU4bokW8xaF5MgBiQOAKirH3q2TLZBtvYO/VLIovM8Z9GOQA6K5nt8nc0xivvvUhHIyPkjZ/gWf/cLs1ZlP6BxSTMHsMTLRGrjJmwYQpn4IFo/NzLf4l/IRNH5EaTfUZXlbvtz9JnvekCf1NoWTx7PD3cKljPsuz61kmPMM36biOpxL8Yn0A6wmiI3YfzGhDe2KnyFGjykE1uwVHc0NKt818CmX8/ppQoG9Ntbu/M4VMpdy3qhs3X00P0R1Wzenw5ET8/8FyYrWhD6XVdI094drz3bVl9v5OhaoPUTz5TaeSnGnp0hF/7sqxzEf5iBd+/wrwywM4LNsuQEXb08EAQX8zoL9ULbQk+oE1z6iEyzt5AQs/Uh05LQP/qswYThImgFl3wBCow/lbI1Z2tXnx/acyTzLMYKHSvtitLX0RtflDSQODVwsarSTOinHJURMT/uc=
